spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: false

server:
  error:
    include-message: never
    include-binding-errors: never

management:
  endpoint:
    health:
      show-details: when_authorized
